import 'package:flutter/material.dart';

const String _lastUpdated = 'Not yet published — draft';

class TermsOfServiceScreen extends StatelessWidget {
  const TermsOfServiceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0D0F1A),
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: const Text('Terms of Service', style: TextStyle(color: Colors.white)),
        iconTheme: const IconThemeData(color: Colors.white),
      ),
      body: ListView(
        padding: const EdgeInsets.all(20),
        children: [
          _draftNotice(),
          const SizedBox(height: 24),
          _paragraph('Last updated: $_lastUpdated'),
          const SizedBox(height: 20),
          _paragraph(
            "These terms govern your use of Ollie. By creating an account or using the "
            "app, you agree to them. If you don't agree, please don't use Ollie.",
          ),
          _section('What Ollie is', [
            _bullet('Ollie is an AI companion app. Everything Ollie says is generated by '
                'an AI model — Ollie is not a real person, not a licensed therapist or '
                'counselor, and not a medical, legal, or financial professional.'),
            _bullet('Ollie is built for everyday companionship and emotional support, not '
                'as a substitute for professional care. Nothing Ollie says should be taken '
                'as medical, mental health, legal, or financial advice.'),
          ]),
          _section('Not a crisis service', [
            _bullet('Messages are automatically screened for signs of self-harm, abuse, or '
                'crisis, and Ollie is designed to respond with care and point toward real '
                'help when that happens — but Ollie is not an emergency service and this '
                'screening is not a guarantee.'),
            _bullet('If you are in crisis or facing an emergency, contact local emergency '
                'services or a crisis line directly. Do not rely on Ollie for anything '
                'time-critical or life-threatening.'),
          ]),
          _section('Who can use Ollie', [
            _bullet('You must be at least 13 years old to use Ollie.'),
            _bullet('You\'re responsible for the accuracy of the information you provide '
                'when creating an account, and for keeping your password secure.'),
          ]),
          _section('Free tier & Premium', [
            _bullet('The free tier includes a limited number of messages per day. Premium '
                'subscriptions (monthly, yearly, or lifetime) remove that limit and unlock '
                'additional features.'),
            _bullet('Subscriptions are billed and managed through Google Play Billing. '
                'Auto-renewing subscriptions renew automatically until cancelled — cancel '
                'any time through your Google Play account. Refunds are handled under '
                'Google Play\'s own refund policy, not directly by us.'),
            _bullet('Watching a rewarded ad is optional and unlocks bonus messages on the '
                'free tier.'),
            _bullet('Prices and what\'s included in each tier may change; we\'ll make '
                'reasonable efforts to let you know before changes that affect an active '
                'subscription.'),
          ]),
          _section('Acceptable use', [
            _bullet('Don\'t use Ollie for anything illegal, to harass or harm others, or to '
                'attempt to extract, abuse, or manipulate the underlying AI systems in ways '
                'that violate these terms.'),
            _bullet('Don\'t try to access other users\' accounts or data, reverse-engineer '
                'the app, or interfere with the service\'s normal operation.'),
            _bullet('We may suspend or terminate accounts that violate these terms.'),
          ]),
          _section('Your content', [
            _bullet('You own what you send Ollie. Using the app gives us permission to '
                'process your messages as described in the Privacy Policy — to generate '
                'replies, remember context, and run safety screening.'),
            _bullet('Ollie\'s replies are generated by AI and may sometimes be inaccurate, '
                'out of character, or inappropriate. Use your own judgment.'),
          ]),
          _section('Your account', [
            _bullet('You can delete your account at any time from Settings. Deletion goes '
                'through a short grace period before it\'s permanent — see the in-app '
                'deletion flow for exact details.'),
            _bullet('If you have an active Premium subscription, deleting your account '
                'doesn\'t automatically cancel billing — cancel separately through Google '
                'Play.'),
          ]),
          _section('Disclaimers', [
            _bullet('Ollie is provided "as is," without warranties of any kind. We don\'t '
                'guarantee the app will be uninterrupted, error-free, or that Ollie\'s '
                'responses will always be accurate or appropriate.'),
            _bullet('To the fullest extent permitted by law, we aren\'t liable for indirect, '
                'incidental, or consequential damages arising from your use of the app, or '
                'for the content of Ollie\'s AI-generated responses.'),
          ]),
          _section('Changes to these terms', [
            _bullet('If these terms change in a way that matters, we\'ll let you know in '
                'the app. Continuing to use Ollie after a change means you accept the '
                'updated terms.'),
          ]),
          _section('Governing law', [
            _bullet('[Insert governing law / jurisdiction here before publishing.]'),
          ]),
          _section('Contact us', [
            _bullet('Questions about these terms: [add a real contact email before publishing].'),
          ]),
          const SizedBox(height: 12),
          _draftNotice(),
          const SizedBox(height: 24),
        ],
      ),
    );
  }

  Widget _draftNotice() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: const Color(0xFFFFB74D).withOpacity(0.12),
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: const Color(0xFFFFB74D).withOpacity(0.4)),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Icon(Icons.warning_amber_rounded, color: Color(0xFFFFB74D), size: 20),
          const SizedBox(width: 12),
          Expanded(
            child: Text(
              "This is a draft that reflects what the app actually does, generated to give "
              "you a starting point — not legal advice. Have it reviewed by a lawyer before "
              "you publish the app, especially the liability and governing-law sections.",
              style: TextStyle(color: Colors.white.withOpacity(0.85), fontSize: 13, height: 1.4),
            ),
          ),
        ],
      ),
    );
  }

  Widget _section(String title, List<Widget> bullets) {
    return Padding(
      padding: const EdgeInsets.only(top: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600),
          ),
          const SizedBox(height: 10),
          ...bullets,
        ],
      ),
    );
  }

  Widget _bullet(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Padding(
            padding: const EdgeInsets.only(top: 6),
            child: Container(
              width: 4,
              height: 4,
              decoration: BoxDecoration(color: Colors.white.withOpacity(0.5), shape: BoxShape.circle),
            ),
          ),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              text,
              style: TextStyle(color: Colors.white.withOpacity(0.75), fontSize: 14, height: 1.5),
            ),
          ),
        ],
      ),
    );
  }

  Widget _paragraph(String text) {
    return Text(
      text,
      style: TextStyle(color: Colors.white.withOpacity(0.75), fontSize: 14, height: 1.5),
    );
  }
}
